// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-bvO3XhlJyj428_4Yf2f-BGcZYBmLQ8',
    appId: '1:440588486666:web:a1ceda8e5f2a1455f8f7f3',
    messagingSenderId: '440588486666',
    projectId: 'flutterfire-79ec7',
    authDomain: 'flutterfire-79ec7.firebaseapp.com',
    storageBucket: 'flutterfire-79ec7.appspot.com',
    measurementId: 'G-KWYNNKPL4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfrb3V-rXLrXR-Hj39gwKGqFGMPo8ln6Y',
    appId: '1:440588486666:android:08d7352073d3bfb9f8f7f3',
    messagingSenderId: '440588486666',
    projectId: 'flutterfire-79ec7',
    storageBucket: 'flutterfire-79ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAppXwe1tvutDXNX9NVvLkqU7tHDUKqZe0',
    appId: '1:440588486666:ios:b2e99be343b3e2f0f8f7f3',
    messagingSenderId: '440588486666',
    projectId: 'flutterfire-79ec7',
    storageBucket: 'flutterfire-79ec7.appspot.com',
    iosClientId: '440588486666-gmt17lo2kh6dfb29cqt0oju4fiot3bgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAppXwe1tvutDXNX9NVvLkqU7tHDUKqZe0',
    appId: '1:440588486666:ios:b2e99be343b3e2f0f8f7f3',
    messagingSenderId: '440588486666',
    projectId: 'flutterfire-79ec7',
    storageBucket: 'flutterfire-79ec7.appspot.com',
    iosClientId: '440588486666-gmt17lo2kh6dfb29cqt0oju4fiot3bgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );
}